server:
  port: 8080
spring:
  profiles:
    active: ${env:dev}
  application:
    name: alexss-desafio-bb-cotacao-api
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quote?useSSL=false
    username: userdb
    password: userdb
    platform: mysql
    initialization-mode: always
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl.auto: update
entitymanager.packagesToScan:
logging:
  level:
    com.alelo.adq.gal.rpt.accounting.api: DEBUG
olinda:
  service:
    url: https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/CotacaoDolarDia(dataCotacao=@dataCotacao)
    connect.timeout: 5000
    read.timeout: 5000
---
spring:
  profiles: dev
  application:
    name: alexss-desafio-bb-cotacao-api
    datasource:
      url: jdbc:mysql://localhost:3306/quotadb?useSSL=false
      username: userdb
      password: userdb
      platform: mysql
      initialization-mode: always
      hikari:
        connectionTimeout: 20000
        maximumPoolSize: 5
logging:
  level:
    com.alelo.adq.gal.rpt.accounting.api: DEBUG
olinda:
  service:
    url: https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/CotacaoDolarDia(dataCotacao=@dataCotacao)
    connect.timeout: 5000
    read.timeout: 5000
---
spring:
  profiles: hml
  application:
    name: alexss-desafio-bb-cotacao-api
    datasource:
      url: jdbc:mysql://localhost:3306/quotadb?useSSL=false
      username: userdb
      password: userdb
      platform: mysql
      initialization-mode: always
      hikari:
        connectionTimeout: 20000
        maximumPoolSize: 5
logging:
  level:
    com.alelo.adq.gal.rpt.accounting.api: INFO
olinda:
  service:
    url: https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/CotacaoDolarDia(dataCotacao=@dataCotacao)
    connect.timeout: 5000
    read.timeout: 5000

---
spring:
  profiles: prd
  application:
    name: alexss-desafio-bb-cotacao-api
    datasource:
      url: jdbc:mysql://localhost:3306/quotadb?useSSL=false
      username: userdb
      password: userdb
      platform: mysql
      initialization-mode: always
      hikari:
        connectionTimeout: 20000
        maximumPoolSize: 5
logging:
  level:
    com.alelo.adq.gal.rpt.accounting.api: INFO
olinda:
  service:
    url: https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/CotacaoDolarDia(dataCotacao=@dataCotacao)
    connect.timeout: 5000
    read.timeout: 5000
