-- MySQL Script generated by Alexandre S. Silva (Alexss)
-- Sat 26 Sep 2020 07:14:37 PM

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema counter_currency
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `quote` ;

-- -----------------------------------------------------
-- Schema counter_currency
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quote` DEFAULT CHARACTER SET utf8 ;
USE `quote` ;

-- -----------------------------------------------------
-- Table `counter_currency`.`quote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quote`.`counter_currency` ;

CREATE TABLE IF NOT EXISTS `quote`.`counter_currency` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `requestTimestamp` TIMESTAMP NOT NULL,
  `dateQuotation` DATE NOT NULL,
  `purchasePrice` DECIMAL(15,3) NOT NULL,
  `salesQuote` DECIMAL(15,3) NOT NULL ,
  `dateTimeQuotation` TIMESTAMP NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update` TIMESTAMP NULL,
  PRIMARY KEY (`id`)) ENGINE = InnoDB;